version: '3'

services:
  terraform:
    image: hashicorp/terraform:light
    container_name: terraform
    environment:
      - VAULT_TOKEN=${VAULT_DEV_ROOT_TOKEN_ID}
    depends_on:
      - db
      - vault
    volumes:
      - ./terraform/:/app/
    working_dir: /app/
    command: apply -auto-approve

  vault:
    image: vault:1.11.2
    container_name: ${VAULT_HOST}
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_DEV_ROOT_TOKEN_ID}
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK

  db:
    image: mysql:5.7
    container_name: ${MYSQL_HOST}
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
